"""Migration Playbook Generator — step-by-step migration plans."""

import json
import sys
import os
from datetime import datetime

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
from core.chain_health import full_chain_comparison
from core.risk_scorer import compute_migration_risk, get_contract_complexity


def generate_playbook(source: str, target: str, project_name: str = "Your Project") -> str:
    """
    Generate a complete migration playbook with actionable steps.
    """
    # Gather all data
    comparison = full_chain_comparison(source, target)
    risk = compute_migration_risk(source, target)
    complexity = get_contract_complexity(source, target)

    # Determine migration type
    evm_chains = {"ethereum", "bsc", "polygon", "arbitrum", "optimism", "base", "avalanche", "fantom"}
    source_is_evm = source.lower() in evm_chains
    target_is_solana = target.lower() == "solana"
    both_evm = source.lower() in evm_chains and target.lower() in evm_chains

    src = comparison.get("source_chain", {}) if "source_chain" in comparison else {}
    tgt = comparison.get("target_chain", {}) if "target_chain" in comparison else {}

    now = datetime.utcnow().strftime("%Y-%m-%d")

    playbook = f"""# 📋 Migration Playbook: {project_name}
## {source} → {target}
*Generated by MigrateAI on {now}*

---

## 📊 Executive Summary

| Metric | Value |
|--------|-------|
| **Feasibility Grade** | {comparison.get('feasibility_grade', 'N/A')} ({comparison.get('feasibility_score', 'N/A')}/100) |
| **Risk Level** | {risk.get('risk_level', 'N/A')} ({risk.get('overall_risk_score', 'N/A')}/100) |
| **Complexity** | {complexity.get('difficulty_level', 'N/A')} |
| **Estimated Duration** | {complexity.get('estimated_weeks', 'N/A')} weeks |
| **Requires Full Rewrite** | {'Yes ⚠️' if complexity.get('requires_rewrite') else 'No ✅'} |

### Source: {source}
- TVL: {src.get('tvl_formatted', 'N/A')} | Protocols: {src.get('protocol_count', 'N/A')} | Trend: {src.get('tvl_trend', 'N/A').upper()}

### Target: {target}
- TVL: {tgt.get('tvl_formatted', 'N/A')} | Protocols: {tgt.get('protocol_count', 'N/A')} | Trend: {tgt.get('tvl_trend', 'N/A').upper()}

---

## ⚠️ Key Challenges
"""
    for challenge in risk.get("challenges", []):
        severity_emoji = {"HIGH": "🔴", "MEDIUM": "🟡", "LOW": "🟢"}.get(challenge["severity"], "⚪")
        playbook += f"\n### {severity_emoji} {challenge['issue']} ({challenge['severity']})\n{challenge['detail']}\n"

    # Phase 1: Assessment
    playbook += """
---

## 📋 Phase 1: Assessment & Planning (Week 1-2)

### 1.1 Audit Current Deployment
- [ ] Document all deployed contracts on source chain
- [ ] Map contract interactions and dependencies
- [ ] Identify external integrations (oracles, bridges, other protocols)
- [ ] Export current contract state (balances, positions, configs)
- [ ] Review governance/admin controls and multisig setup

### 1.2 Target Chain Research
- [ ] Study target chain's account/execution model
- [ ] Identify equivalent token standards and libraries
- [ ] Find target chain's DEX/AMM ecosystem for liquidity
- [ ] Research oracle providers available on target chain
- [ ] Join target chain's developer Discord/community

### 1.3 Bridge Strategy
- [ ] Confirm Wormhole NTT support for token bridging
- [ ] Evaluate alternative bridges (LayerZero, CCTP, Axelar)
- [ ] Design token supply management (burn-and-mint vs lock-and-mint)
- [ ] Plan liquidity bootstrapping on target chain
"""

    # Phase 2: Development (varies by complexity)
    if both_evm:
        playbook += """
## 🔨 Phase 2: Development (Week 2-4)

### 2.1 Contract Migration (EVM → EVM)
- [ ] Deploy existing contracts to target chain testnet
- [ ] Adjust for chain-specific differences (gas costs, block times)
- [ ] Update hardcoded addresses (tokens, routers, oracles)
- [ ] Verify oracle feed availability on target chain
- [ ] Run full test suite on target chain testnet

### 2.2 Infrastructure
- [ ] Set up RPC endpoints for target chain
- [ ] Update frontend to support target chain
- [ ] Configure wallet connections (RainbowKit/wagmi update)
- [ ] Set up monitoring and alerting
"""
    elif source_is_evm and target_is_solana:
        playbook += f"""
## 🔨 Phase 2: Development (Week 2-{int(complexity.get('estimated_weeks', '16').split('-')[1])})

### 2.1 Architecture Redesign
- [ ] Redesign data model for Solana's account-based storage
- [ ] Map each contract's state to Program Derived Addresses (PDAs)
- [ ] Design instruction set (Solana's equivalent of contract functions)
- [ ] Plan account ownership and authority structure

### 2.2 Smart Contract Rewrite (Solidity → Anchor/Rust)
- [ ] Set up Anchor project structure
- [ ] Implement core program logic in Rust
- [ ] Implement token interactions via SPL Token / Token-2022
- [ ] Replace EVM events with Anchor events
- [ ] Replace access control with Solana signers/authority pattern
- [ ] Implement CPI (Cross-Program Invocation) for composability

### 2.3 Testing
- [ ] Unit tests with Anchor test framework
- [ ] Integration tests on Solana devnet
- [ ] Fuzzing with Trident or custom fuzzers
- [ ] Security audit (consider Sec3, OtterSec, Neodyme)

### 2.4 Frontend Migration
- [ ] Replace ethers.js/viem with @solana/web3.js
- [ ] Implement wallet adapter (Phantom, Backpack, Solflare)
- [ ] Update transaction signing flow
- [ ] Add Solana-specific UI patterns (account creation prompts, etc.)
"""
    else:
        playbook += f"""
## 🔨 Phase 2: Development (Week 2-{complexity.get('estimated_weeks', 'TBD').split('-')[-1]})

### 2.1 Contract Development
- [ ] Study target chain's smart contract language and patterns
- [ ] Redesign contract architecture for target chain
- [ ] Implement core logic in target chain's native language
- [ ] Set up testing infrastructure

### 2.2 Testing
- [ ] Deploy and test on target chain testnet
- [ ] Run comprehensive test suite
- [ ] Consider security audit
"""

    # Phase 3: Token Migration
    playbook += """
## 🌉 Phase 3: Token & Liquidity Migration

### 3.1 Token Bridge Setup
- [ ] Deploy Wormhole NTT Manager contracts (if applicable)
- [ ] Configure burn-and-mint or lock-and-mint strategy
- [ ] Set rate limits for bridge transfers
- [ ] Test bridge with small amounts on testnet

### 3.2 Liquidity Migration
- [ ] Seed initial liquidity on target chain DEX (Jupiter for Solana, etc.)
- [ ] Set up liquidity mining / incentive program for early migrants
- [ ] Coordinate with bridge aggregators (LiFi, Socket) for routing
- [ ] Plan migration timeline with existing liquidity providers

### 3.3 User Migration
- [ ] Announce migration timeline to community (>2 weeks notice)
- [ ] Provide step-by-step migration guide for users
- [ ] Set up migration dashboard showing progress
- [ ] Offer migration incentives (bonus tokens, reduced fees)
"""

    # Phase 4: Launch
    playbook += """
## 🚀 Phase 4: Launch & Post-Migration

### 4.1 Mainnet Deployment
- [ ] Deploy contracts to target chain mainnet
- [ ] Verify and publish contract source code
- [ ] Enable bridge for token transfers
- [ ] Open liquidity pools

### 4.2 Monitoring
- [ ] Monitor bridge flows and token supply integrity
- [ ] Track user migration progress
- [ ] Watch for bridge exploits or anomalies
- [ ] Monitor gas costs and compute usage

### 4.3 Source Chain Sunset
- [ ] Set deprecation timeline for source chain contracts
- [ ] Implement emergency withdrawal on source chain
- [ ] Eventually pause/freeze source chain contracts
- [ ] Final state snapshot for records

---

## 🔗 Resources

- Wormhole NTT Docs: https://wormhole.com/docs/products/token-transfers/native-token-transfers/
- Wormhole NTT GitHub: https://github.com/wormhole-foundation/native-token-transfers
- DeFi Llama Bridge Data: https://defillama.com/bridges
- WormholeScan Explorer: https://wormholescan.io/
"""

    if target_is_solana:
        playbook += """- Solana EVM to SVM Guide: https://solana.com/news/evm-to-svm
- Solana Developer Docs: https://solana.com/developers
- Anchor Framework: https://www.anchor-lang.com/
- Sunrise (Wormhole): Asset onboarding to Solana with day-one liquidity
"""

    playbook += f"""
---
*Report generated by MigrateAI v0.1 — AI-Powered Cross-Chain Migration Analyzer*
*Data sources: DeFi Llama, WormholeScan, Solana/Ethereum RPCs*
"""

    return playbook


if __name__ == "__main__":
    if len(sys.argv) > 2:
        source = sys.argv[1]
        target = sys.argv[2]
        name = sys.argv[3] if len(sys.argv) > 3 else "Your Project"
        print(generate_playbook(source, target, name))
    else:
        print("Usage: python playbook.py <source_chain> <target_chain> [project_name]")
        print("Example: python playbook.py Fantom Solana 'SpookySwap'")
